[build.environment]
  DART_SASS_VERSION = "1.70.0"
  HUGO_VERSION = "0.122.0"
  HUGO_ENV = "production"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://hugo-theme-nightfall.netlify.com"

[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --themesDir .. --theme $HUGO_THEME --baseURL $HUGO_BASEURL"

[[plugins]]
  package = "netlify-plugin-dartsass"

